classDiagram
    Artist "1" --o "*" Album : artistId

    class Artist {
        -String id
        +String name
    }
    class Album { 
        -String id
        -String pathId
        -String pathUrlAudio
        -Enum status
        +String artistId
        +String name
        +String year
        +String url
        -CreateAlbum()
        -writeFileStream()
    }
            